import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/frame/footer/Footer";
import Header from "@/components/frame/header/Header";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import myFont from "@/utils/fonts";
import Modal from "@/app/Modal";

export const metadata: Metadata = {
  title: "RP-clothing",
  description: "Generated by create next app",
  // FIXME: アイコンが入ります
  // icons: {
  //   icon: "/images/favicon.ico",
  // },
};

export default function RootLayout({
  children,
  search
}: Readonly<{
  children: React.ReactNode,
  search: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${myFont.className}`}>
        <Header />
        <ToastContainer />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
