import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/frame/header/Header";
import Footer from "@/components/frame/footer/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import styles from "@/components/frame/footer/Footer.module.css";

const geistSans = localFont({
  src: "./fonts/ArbutusSlab-Regular.ttf",
  variable: "--font-geist-sans",
  weight: "400",
  style: "normal",
});

const geistMono = localFont({
  src: "./fonts/ArbutusSlab-Regular.ttf",
  variable: "--font-geist-mono",
  weight: "400",
  style: "normal",
});

export const metadata: Metadata = {
  title: "RP-clothing",
  description: "Generated by create next app",
  // FIXME: アイコンが入ります
  // icons: {
  //   icon: "/images/favicon.ico",
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={styles.wrapper}>
          <Header />
          <ToastContainer />
          <main className={styles.content}>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
