name: CI

on:
  push:

jobs:
  run-nextjs-ci:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Set up .env
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "RAKUTEN_API_ID=${{ secrets.RAKUTEN_API_ID }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "REDIS_URL=redis://127.0.0.1:6379" >> .env
          echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}" >> .env
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env

      - name: Start Next.js server
        run: npm run dev &
        env:
          PORT: 3000

      - name: Wait for localhost:3000
        run: |
          echo "Waiting for server to start..."
          for i in {1..30}; do
            curl -sSf http://localhost:3000 > /dev/null && echo "Server is up!" && break
            echo "Server is not ready yet. Retrying in 2 seconds..."
            sleep 2
          done

      - name: Check Format
        run: npm run format

      - name: Check Lint
        run: npm run lint

      - name: Cache delete
        run: npm cache clean --force

      - name: Build
        run: npm run build

      - name: Verify Build Artifacts
        run: |
          test -d .next && echo "Build artifacts found: .next directory exists" || exit 1

      - name: Test
        run: npm test
